### PR TITLE
token auth

### PR DESCRIPTION
**Pull request by dandds**
This is a blunt implementation of the token auth headers relevant to [this](https://www.pivotaltracker.com/story/show/158461535) PT story.

The original outline mentioned using an HMAC-SHA1, but SHA1 is deprecated so I've used SHA256. 

It would be nice to flesh this out into a better open source library (make required headers/fields configurable, support a few different frameworks besides Flask, etc.) but this should be sufficient for our initial needs.

### CODE REVIEW

**Comment by ddsdevon** [comment]
@dandds I'd like to see pylint and bandit added in to keep an eye on code quality.

Do you think it is worth pulling in the shared scripts for now, to leverage the setup, update, and test scripts we're already using else where? It should allow for a comparable Travis config and make the process of making changes to the library a bit more cookie-cutter. 
Since it is a library with only demo code, I wouldn't expect /script/server or anything like that... though I suppose you could have /script/demo_server and /script/demo_client

Also, do we want to push this to PyPI, or is there some other distribution method you had in mind for pulling the library into the other app(s)?

**Comment by dandds** [comment]
@ddsdevon Added a few commits to address your feedback. 

I'm not sure about distribution. We could just put it on PyPi, or we could just use the Git URL in the Pipfiles of projects that need it. (I think we probably need some packaging boilerplate either way.)

**Comment by ddsdevon** [comment]
@dandds Looks good for my side of things! Setup and tests run out of the gate on a fresh clone, and the demo seems to work just fine.
I'll have to defer Python code review to @patricksmithdds, @richard-dds, @jordangov, or @kristiandds though 😸

**Comment by jordangov** [comment]
Code looks fine to me.

**Review by jordangov — APPROVED** [review]

**Pull request merged**
